# Generated by Django 4.0.2 on 2022-03-22 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='review',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='uslug',
        ),
        migrations.AlterField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.movie'),
        ),
        migrations.RemoveField(
            model_name='review',
            name='author',
        ),
    ]
