# Generated by Django 4.0.2 on 2022-03-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_review_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='movie_name',
            field=models.CharField(default='Harry Potter 8', max_length=255),
        ),
    ]
