# Generated by Django 4.0.2 on 2022-03-29 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_watch'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='poster_url',
            field=models.URLField(default='https://image.tmdb.org/t/p/original', max_length=255),
        ),
        migrations.AddField(
            model_name='watch',
            name='poster_url',
            field=models.URLField(default='https://image.tmdb.org/t/p/original', max_length=255),
        ),
    ]
